# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timeseries.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='timeseries.proto',
  package='stream',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10timeseries.proto\x12\x06stream\"2\n\x0cNiftyRequest\x12\x11\n\tstartDate\x18\x01 \x01(\x03\x12\x0f\n\x07\x65ndDate\x18\x02 \x01(\x03\",\n\rNiftyResponse\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x01\x32L\n\x0cNiftyService\x12<\n\tNiftyCall\x12\x14.stream.NiftyRequest\x1a\x15.stream.NiftyResponse\"\x00\x30\x01\x62\x06proto3'
)




_NIFTYREQUEST = _descriptor.Descriptor(
  name='NiftyRequest',
  full_name='stream.NiftyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='startDate', full_name='stream.NiftyRequest.startDate', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endDate', full_name='stream.NiftyRequest.endDate', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=78,
)


_NIFTYRESPONSE = _descriptor.Descriptor(
  name='NiftyResponse',
  full_name='stream.NiftyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='stream.NiftyResponse.date', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='stream.NiftyResponse.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['NiftyRequest'] = _NIFTYREQUEST
DESCRIPTOR.message_types_by_name['NiftyResponse'] = _NIFTYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NiftyRequest = _reflection.GeneratedProtocolMessageType('NiftyRequest', (_message.Message,), {
  'DESCRIPTOR' : _NIFTYREQUEST,
  '__module__' : 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:stream.NiftyRequest)
  })
_sym_db.RegisterMessage(NiftyRequest)

NiftyResponse = _reflection.GeneratedProtocolMessageType('NiftyResponse', (_message.Message,), {
  'DESCRIPTOR' : _NIFTYRESPONSE,
  '__module__' : 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:stream.NiftyResponse)
  })
_sym_db.RegisterMessage(NiftyResponse)



_NIFTYSERVICE = _descriptor.ServiceDescriptor(
  name='NiftyService',
  full_name='stream.NiftyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=126,
  serialized_end=202,
  methods=[
  _descriptor.MethodDescriptor(
    name='NiftyCall',
    full_name='stream.NiftyService.NiftyCall',
    index=0,
    containing_service=None,
    input_type=_NIFTYREQUEST,
    output_type=_NIFTYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NIFTYSERVICE)

DESCRIPTOR.services_by_name['NiftyService'] = _NIFTYSERVICE

# @@protoc_insertion_point(module_scope)
