version: '3'
services:
  server:
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - 8010:8010
  client:
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
      - 8011:8011
  web:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - 8080:80