# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import timeseries_pb2 as timeseries__pb2


class NiftyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NiftyCall = channel.unary_stream(
                '/stream.NiftyService/NiftyCall',
                request_serializer=timeseries__pb2.NiftyRequest.SerializeToString,
                response_deserializer=timeseries__pb2.NiftyResponse.FromString,
                )


class NiftyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NiftyCall(self, request, context):
        """an example of getting a feature
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NiftyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NiftyCall': grpc.unary_stream_rpc_method_handler(
                    servicer.NiftyCall,
                    request_deserializer=timeseries__pb2.NiftyRequest.FromString,
                    response_serializer=timeseries__pb2.NiftyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stream.NiftyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NiftyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NiftyCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stream.NiftyService/NiftyCall',
            timeseries__pb2.NiftyRequest.SerializeToString,
            timeseries__pb2.NiftyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
